// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJDLkGiGj9JTDhEJS3Im7RUc_8kOVAK-A',
    appId: '1:234435414851:web:ac7341129f0860136ebdf6',
    messagingSenderId: '234435414851',
    projectId: 'yg-coding-chatting',
    authDomain: 'yg-coding-chatting.firebaseapp.com',
    storageBucket: 'yg-coding-chatting.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGGvSo4yiGDGEnbLV2Tu0mCdeEeha33gY',
    appId: '1:234435414851:android:58691a386df5db476ebdf6',
    messagingSenderId: '234435414851',
    projectId: 'yg-coding-chatting',
    storageBucket: 'yg-coding-chatting.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZnQiPr-jK3NOrMGh1J5JpsV7y14CuzPU',
    appId: '1:234435414851:ios:fb112bfa037927186ebdf6',
    messagingSenderId: '234435414851',
    projectId: 'yg-coding-chatting',
    storageBucket: 'yg-coding-chatting.appspot.com',
    iosBundleId: 'com.example.firstproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZnQiPr-jK3NOrMGh1J5JpsV7y14CuzPU',
    appId: '1:234435414851:ios:0a63b05820eda9ad6ebdf6',
    messagingSenderId: '234435414851',
    projectId: 'yg-coding-chatting',
    storageBucket: 'yg-coding-chatting.appspot.com',
    iosBundleId: 'com.example.firstproject.RunnerTests',
  );
}
